### ISSUE TITLE
construct validation rules before supplying data

### ISSUE THREAD

**Issue by alexweissman** [vlucas/valitron#108]
At the moment, Valitron has to be initialized with an array of field->value mappings.  So, there is no way to add data to be validated after initialization.  Any thoughts on adding a `setData` method?

**Comment by geggleto** [comment]
sorry to drag this up, but here is my use-case.

I use valitron in middlewares...

I define all of the Validation rules in my DIC. In order to do this I have to initialize Valitron with a constructor. For me I take the current request object and get the ParsedBody. My only gripe is that I cannot validate anything else my middlewares might add to the request object.

It would be better to have setData as I could set the data-set in my middleware with the current Request object's data rather than relying on what the framework discovered at application bootstrap.

**Comment by nebulousGirl** [comment]
From what @vlucas was saying, it might be better to add a method `withData` that would clone the object and return a new instance.

**Comment by willemwollebrants** [comment]
@geggleto : don't be sorry :) It's a great feature that is long overdue.
@nebulousGirl : I'm leaning towards that too, a bit of a immutable approach might prevent a lot of problems

I'm busy putting both of them out on the "setdata" branch at the moment, come check it out (work in progress)

**Comment by wenbinye** [comment]
@willemwollebrants withData does not work, because the reset function clear validations too.

**Comment by willemwollebrants** [comment]
Thanks @wenbinye : you're absolutely right. Will fix immediately (both the code and the test)
