### ISSUE TITLE
min and max throw an error if the value is an array

### ISSUE THREAD

**Issue by thinkjson** [vlucas/valitron#149]
I get the following error if the value being tested is an array:

	Stacktrace (most recent call first):

	  File "/vendor/vlucas/valitron/src/Valitron/Validator.php", line 320, in handleErrors
	    return !(bccomp($params[0], $value, 14) == 1);
	  File "/vendor/vlucas/valitron/src/Valitron/Validator.php", line 320, in validateMin
	    return !(bccomp($params[0], $value, 14) == 1);
	  File "/vendor/vlucas/valitron/src/Valitron/Validator.php", line 878, in validate
	    $result = $result && call_user_func($callback, $field, $value, $v['params']);
	...
	bccomp() expects parameter 2 to be string, array given

The fix could probably be as easy as returning false from the beginning of the validation function if the value returns false from is_numeric.

**Comment by willemwollebrants** [comment]
Hm, I don't think the problem is with the value being tested, the value itself is tested with is_numeric first

I did some test:
`
$validator=  new Valitron\Validator(["foo"=>1]);
$validator->rule("min", "foo", 10);
var_dump($validator->validate()); // false because 1 < 10

$validator=  new Valitron\Validator(["foo"=>[1]]);
$validator->rule("min", "foo", 10);
var_dump($validator->validate()); // false because [1] is not numeric`

Those seem to work. To reproduce the error I tried the following:
`$validator=  new Valitron\Validator(["foo"=>1]);
$validator->rule("min", "foo", [10]);
$validator->validate() ;`

So the third parameter should be numeric also. If it's not I think it would be better to throw an \InvalidArgumentException instead of returning false: if we just return false it would seem like the validation ran and failed, causing headaches and bugs.

What do you think?

**Comment by thinkjson** [comment]
This is the case where I thought the validator should just return false:

	php > $validator =  new Valitron\Validator(["foo"=>["potato"]]);
	php > $validator->rule("min", "foo", 10);
	php > var_dump($validator->validate());
	PHP Warning:  bccomp() expects parameter 2 to be string, array given in /cdn/cdnws/current/vendor/vlucas/valitron/src/Valitron/Validator.php on line 320
	PHP Stack trace:
	PHP   1. {main}() php shell code:0
	PHP   2. Valitron\Validator->validate() php shell code:1
	PHP   3. call_user_func:{./vendor/vlucas/valitron/src/Valitron/Validator.php:878}() ./vendor/vlucas/valitron/src/Valitron/Validator.php:878
	PHP   4. Valitron\Validator->validateMin() ./vendor/vlucas/valitron/src/Valitron/Validator.php:878
	PHP   5. bccomp() ./vendor/vlucas/valitron/src/Valitron/Validator.php:320
	bool(true)

Interestingly enough, if I didn't have bcmath installed, validation would have passed:

        php > var_dump(10 <= ["potato"]);
        bool(true)

**Comment by thinkjson** [comment]
See the difference in logic if you have bcmath and if you don't?

    protected function validateMin($field, $value, $params)
     {
         if (function_exists('bccomp')) {
             return !(bccomp($params[0], $value, 14) == 1);
         } else {
             return $params[0] <= $value;
         }
     }

**Comment by thinkjson** [comment]
Oh, you know what? This has been fixed in a later version. The latest version of the function already does the is_numeric check. I'll upgrade.

Here's the relevant commit: https://github.com/vlucas/valitron/commit/96221ea4d3c22f893bec69631b90e050243ee906
