### ISSUE TITLE
bccomp in validateMax and validateMin

### ISSUE THREAD

**Issue by etctschq** [vlucas/valitron#156]
I will use validateMin as my example, but my comments apply to validateMax as well.

I don't believe the bccomp function is necessary in validateMin, unless I misunderstand the purpose of the function. My assumption when validating the minimum value from POST data would be that any value below the parameter provided should return false. This can be done with the $params[0] <= $value behavior that the function defaults to in the absence of bccomp() even with float values.

Even if I am incorrect in my understanding of float handling, the behavior of bccomp and the fallback are not the same:

```
=> false
>>> 1 <= -1
=> false
>>> -1 <= 1
=> true
>>> 1 <= 1
=> true
```

```
>>> !(bccomp(1,1,14)) == 1
=> true
>>> !(bccomp(1,-1,14)) == 1
=> false
>>> !(bccomp(-1,1,14)) == 1
=> false
```

My inclination at the moment would be to submit a pull request that simply removes the bccomp option, but if there is a reason I'm not seeing to use the function, I would welcome being enlightened.

**Comment by willemwollebrants** [comment]
The way I understand it, the bccomp function is used to get better precision when comparing floating point numbers. It's optional because it's part of bcmath which may or may not be enabled (but is highly recommended).

It looks like the parentheses in your examples are off. Here are 3 possibilities for validateMin as an example:
```
!(bccomp(-1, 1, 14) == 1);
=> true
-1 <= 1;
=> true

!(bccomp(1, 1, 14) == 1);
=> true
1 <= 1;
=> true

!(bccomp(1, -1, 14) == 1);
=> false
1 <= -1;
=> false
```
Also, the discussion on the pr where this was added might be of interest https://github.com/vlucas/valitron/pull/61

**Comment by etctschq** [comment]
Oh I see. Don't know how I missed that. Turns out the issue I was having was unrelated to this, but masked by my lack of comprehension on the bccomp front. Thanks for the quick response. I'll try to actually contribute something useful next time.
