### ISSUE TITLE
Email validation - including mail domain check

### ISSUE THREAD

**Issue by spurgeonbj** [vlucas/valitron#159]
Hi,

while discussing email validation in userfrosting/fortress to include a check for the existence of actual email domain using a DNS look up for MX record that would confirm that the email domain is indeed valid (https://github.com/userfrosting/UserFrosting/issues/467) Alex Weissman  suggested updating email validation in valitron.

So, I had modified Valitron\Validator.php validateEmail() as follows to include a domain check as follows:
`    /**
     * Validate that a field is a valid e-mail address
     *
     * @param  string $field
     * @param  mixed  $value
     * @return bool
     */
    protected function validateEmail($field, $value) {
        // validate email pattern and domain
        list($user, $domain) = split('@', $value);
        return (checkdnsrr($domain, 'MX') && (filter_var($value, \FILTER_VALIDATE_EMAIL) !== false) );
    }`

This accepts only valid email domains.

Would request to kindly consider for inclusion if you think it is worthwhile.

Thanks!
Spurgeon

**Comment by alexweissman** [comment]
Well actually, I suggested adding it as a separate rule.  There are definitely cases where we might want to only validate syntax, without taking the time to ping a DNS server.

**Comment by spurgeonbj** [comment]
Sure!
Sounds good! You have a valid point.
Thanks once again!

**Comment by willemwollebrants** [comment]
It could become an option for the email-validator too probably:
`$v->rule('email', 'email', true);`
I wouldn't include it by default, because doing the dns lookup can actually take quite some time it seems.

A separate filter would work great I think. I'm thinking of adding support for whitelisted/blacklisted domains as options in that case. (No need to validate if gmail.com has an MX record for example)

A few other remarks:
- I think it's better to first check if it's a valid address according to filter_var($value, \FILTER_VALIDATE_EMAIL) before looking up the dns. No point in checking the domain for something that clearly isn't an e-mail address :)
- dns is "best effort", so checking the dns record is not a 100% reliable substitute for the good old "send mail with link" confirmation/validation a lot of sites use
- The dns lookup will fail if the machine is not connected to the Internet. Most php probably runs on a webserver, but if someone uses it in a cli script this might reject valid e-mail addresses
- Mail delivery can use the A record as a fallback, so we need to consider this too
- Since doing a dns lookup is more expensive than the filter_var method, this might open a vector for a ddos attack: doing the lookup with a non-existant domain takes a long time, so if a hacker sends a lot of non-existing domains you might be in trouble.

So I think it's an interesting idea that might get added after some modifications, but I would not make the mx-check active by default. And, on a personal note, I would not activate the option on scripts on my own server, to be honest.

**Comment by spurgeonbj** [comment]
Hi Willem, Thanks for the kind consideration and words of wisdom. Sounds
perfect! Alex Weissman also suggests on the same lines. Thanks for
enlightening on the other sides of the issue.

**Comment by the94air** [comment]
can you show me the code for mail domain validation as a custom rule

**Comment by the94air** [comment]
+1

**Comment by the94air** [comment]
This is custom rule

```
use Valitron\Validator;

// Custom Validator Rules
Validator::addRule('realEmail', function ($field, $value, array $params, array $fields) {

	$email = $fields[$field];

	$domain = explode("@",$email);

	if(empty($domain[0])) {
		return false;
	} else {

	if(checkdnsrr(array_pop($domain[0]),"MX")){
	return true;
	}else{
	return false;
	}

	}

}, 'adderss is not real');
// will echo ->>>>  Email adderss is not real
```

**Comment by willemwollebrants** [comment]
That's not going to work I'm afraid, you're checking the wrong part:
```php
$parts = explode("@", $value);
$domain = $parts[1];
```
There's no need to use array_pop.

I would urge you to take a look at my reply a bit higher to see some of the downsides of using checkdnsrr, because you will be denying valid e-mail addresses this way.

**Comment by the94air** [comment]
You need to add a dot to the end of the host name to make a fully qualified domain name.
[check this](http://php.net/manual/en/function.checkdnsrr.php#119969)

**Comment by the94air** [comment]
this should work
```
use Valitron\Validator;

// Custom Validator Rules

Validator::addRule('realEmail', function ($field, $value, array $params, array $fields) {

	$email = $fields[$field];

	$Email = explode("@",$email);

	if(!isset($Email[1])) {

		return false;

	} else {

		$domain = $Email[1];
		$domain = $domain . '.';
		return checkdnsrr($domain,"MX");

	}

}, 'adderss is not real');
```

**Comment by zonuexe** [comment]
@the94air 
Please be careful.

@willemwollebrants says https://github.com/vlucas/valitron/issues/159#issuecomment-233192493
> Mail delivery can use the A record as a fallback, so we need to consider this too

This code snippet is not accept `"@"@example.com`.

```php
// This is RFC valid e-mail address and accepted by `filter_var`.
filter_var('"@"@example.com', FILTER_VALIDATE_EMAIL);
// => "\"@\"@example.com"
```

This specification does not affect many users.
But if you do not reject the address containing `"`, a bug occurs on your system.

See Wikipedia. https://en.wikipedia.org/wiki/Email_address#Syntax

-----

The following code is more secure.  (However, I do not recommend it.)

```php
preg_match('/@(?<host>[^@]+)\z/u', $email, $m);
$host_is_ipaddr = filter_var($m['host'], FILTER_VALIDATE_IP) !== false;
if (!$host_is_ipaddr) {
    $domain = $m['host'] . '.';
    // some codes...
}
```

**Comment by the94air** [comment]
it is dangerous. i will not use this rule. :no_entry_sign:
