### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by cwhsu1984** [vlucas/valitron#168]
Hi,

My environment is ubuntu 16.04 and php7.0. I am new to this library, and I just copy and paste the sample codes into a simple class to try it. But the following codes keep looping and cause segmentation fault. Is anything wrong with the codes?
```
<?php                                                                                                                                           

include __DIR__.'/vendor/autoload.php';

class Fetch
{
    public function get()
    {   
        $v = new Valitron\Validator(array("foo" => "bar"));
        $v->rule(function($field, $value, $params, $fields) {
            return true;
        }, "foo")->message("{field} failed...");
        if($v->validate()) {
            echo "Yay! We're all good!";
        } else {
            // Errors
            print_r($v->errors());
        }
    }   
}

$f = new Fetch();

$f->get();
```

Somehow, it keeps looping the user defined callback.

```
PHP Warning:  Illegal offset type in isset or empty in /home/cwhsu/php/vendor/vlucas/valitron/src/Valitron/Validator.php on line 884
PHP Warning:  ucfirst() expects parameter 1 to be string, object given in /home/cwhsu/php/vendor/vlucas/valitron/src/Valitron/Validator.php on line 887
PHP Warning:  Illegal offset type in isset or empty in /home/cwhsu/php/vendor/vlucas/valitron/src/Valitron/Validator.php on line 884
PHP Warning:  ucfirst() expects parameter 1 to be string, object given in /home/cwhsu/php/vendor/vlucas/valitron/src/Valitron/Validator.php on line 887
PHP Warning:  Illegal offset type in isset or empty in /home/cwhsu/php/vendor/vlucas/valitron/src/Valitron/Validator.php on line 884
PHP Warning:  ucfirst() expects parameter 1 to be string, object given in /home/cwhsu/php/vendor/vlucas/valitron/src/Valitron/Validator.php on line 887
PHP Warning:  Illegal offset type in isset or empty in /home/cwhsu/php/vendor/vlucas/valitron/src/Valitron/Validator.php on line 884
Segmentation fault (core dumped)

```

**Comment by willemwollebrants** [comment]
I guess you installed the library using composer? The version there is 1.2.5, but the documentation online is for the upcoming release (1.3 probably, which I really should release soon :/). 

Having a function as the first parameter for the rule() method is new and was not yet possible in v1.2.5, so that's  probably what's causing the problem. 

For now you have 2 options:

- use Valitron\Validator::addRule to add a custom rule (First example [in the documentation here](https://github.com/vlucas/valitron#adding-custom-validation-rules) )
- use the dev branch: `composer require vlucas/valitron:dev-master` 
**Note**: this is not recommended for anything in production.

**Comment by cwhsu1984** [comment]
Hi,

I use `composer require vlucas/valitron`, but I am not going to use dev-master since this is going to be a prod. 

```
    public function get()
    {   
        Valitron\Validator::addRule('foo', function($field, $value, $params, $fields) {
            return false;
        }, "Something failed...");
        $v = new Valitron\Validator(array("foo" => "bar"));
        // not working either...
        //Valitron\Validator::addRule('foo', function($field, $value, $params, $fields) {
        //    return false;
        //}, "Something failed...");
        if($v->validate()) {
            echo "Yay! We're all good!";
        } else {
            // Errors
            print_r($v->errors());
        }
    }  
```
Try to use Valitron\Validator::addRule. It should always fails, but I get "Yay! We're all good!". It looks like the addRule is not working, either.


By the way, I just notice that addRule and rule have different orders in callback's signature.
It's just a bit strange to me. Isn't Valitron\Validator::addRule($field, $callback, $message) and $v->rule($field, $callback, $message) make more sense? Or it could also be $v->rule($field, $callback)->message($message).

```
Valitron\Validator::addRule('alwaysFail', function($field, $value, array $params, array $fields) {
    return false;
}, 'Everything you do is wrong. You fail.');
```
```
$v->rule(function($field, $value, $params, $fields) {
    return true;
}, "foo")->message("{field} failed...");
```

**Comment by willemwollebrants** [comment]
In your example, there is no rule set. The first parameter of Validator::addRule is not the name of the field to check, it's the name of the rule.

You can look at it this way: using Validator::addRule creates the same kind of rules as [the built-in rules](https://github.com/vlucas/valitron/blob/master/README.md#built-in-validation-rules)

I think you want to do this:
```
// add a rule named foo_rule
\Valitron\Validator::addRule('foo_rule',  function($field, $value, $params, $fields) {
return false;
}, "Something failed...");

$v = new \Valitron\Validator(['foo_field'=>'bar']);

// apply foo_rule to our field
$v->rule('foo_rule', ['foo_field']);
```

As for the signature: it's a bit different because the functions are a bit different:

```
//creates a new rule, with a default message
\Valitron\Validator::addRule(Name of the rule, Callback, Default message)
```
vs
```
//binds a rule to a specific set of fields and overwrites the default message
$v->rule(Name of the rule, Field(s))->message(Custom message)
//next version
$v->rule(Callback for the rule, Field(s))->message(Custom message)
```

I think we could (should?) probably have the custom message as a third parameter in $v->rule

**Comment by cwhsu1984** [comment]
Okay, it seems I misunderstand some part of the document. Too bad we couldn't use message by $v->rule, but that's fine. Hope you guys could make the new release soon. Thanks!
