### ISSUE TITLE
use valitron without composer

### ISSUE THREAD

**Issue by asadghazanfary** [vlucas/valitron#179]
hi @vlucas 

how can i use **valitron** without composer?

please help me

**Comment by willemwollebrants** [comment]
Three easy steps: 

1. Go to Code > Releases and download [the zip](https://github.com/vlucas/valitron/archive/v1.3.1.zip) for the latest release
2. Extract it somewhere near your project
3. In your php add `include "path/to/unzipped/files/src/Valitron/Valitron.php"`

(step 0 is consider using composer anyway, because it's totally worth it)

**Comment by hirani89** [comment]
Hi, I tried this but I keep getting an error.

`PHP Fatal error:  require_once(): Failed opening required 'services/modules/api/custom/libraries/valitron/src/Valitron/Validator.php' (include_path='.;C:\php\pear;C:\hmroot\eCase\Webapp') in C:\hmroot\eCase\Webapp\services\modules\api\custom\controllers\RoomAPIController.php on line 8`
