### ISSUE TITLE
PHP Versions (please comment here if you use Valitron)

### ISSUE THREAD

**Issue by willemwollebrants** [vlucas/valitron#186]
As you can see in the ['rules' branch](https://github.com/vlucas/valitron/tree/rules), I'm doing a bit of a cleanup of the existing monolithic Validator class. This might be a good moment to work towards a V2.0, but I would like to drop support for some older PHP-versions:

[Have a look at some of the PHP-versions and their support status](http://php.net/supported-versions.php)

PHP **5.3** and **5.4** have been out of security support for well over a year, and **5.5** has been unsupported for 6 months. 
**5.6** is now in security support, but still used by quite a lot of people. 

I think dropping support for 5.3 is a no-brainer. It's ancient by now and dropping it will give us short array syntax. I would drop 5.4 and 5.5 too, but only if I can get whoever ends up running [vlucas/spot2](https://github.com/vlucas/spot2) to go along with that. On the other end PHP 7.0 and 7.1 should be supported in the near future (It seems to be working out of the box).

Is there any good reason why we should keep supporting 5.3, 5.4 and 5.5 that I'm missing? Most of my projects have been at least on 5.6 for quite some time now, but I'm always interested in hearing your part of the story.

(ps: If you haven't already, be sure to check out PHP 7.+, it's very very good)

**Comment by nebulousGirl** [comment]
I use both Valitron and Spot2 to which I contributed. I'd say any new major version should be at least 5.6. If you can't upgrade your server, just stick to the previous major version.

**Comment by KSVQ** [comment]
I have a situation where I have to retrofit old applications that can't be easily moved to new infrastructure due to: large organization, legacy technology still being in use, massive size systems built in times of PHP5.2,, blah blah blah. For example, I am required to repair and "upgrade" apps built with PHP 5.2. This is NOT an uncommon case for many universities, schools and generally non private sector organizations. So I disagree with the notion that dropping support or at least maintaining retro versions to some degree is a no-brainer. Maybe for someone who never worked on large or older projects that can't just be whipped up in an afternoon,,,

I favor the approach of having older versions of scripts available and fitted with logical improvements but not necessarily built to be equal to new versions.

**Comment by willemwollebrants** [comment]
Thanks for your input @KSVQ ! Just to make it clear: I'm talking about deleting old versions, Valitron v1.x will still be available with support for php 5.3 and up. 

The way I see it, V2.x would not be supporting these old versions but rather take advantage of the newer stuff in php. If we spot a logical error in V1.x it can still be fixed there, but new functions etc. would only be added to the new version. V1.x remains available, but is frozen.

**Comment by KSVQ** [comment]
Oh absolutely. There is no reason to hold back on features for new generation of a tool on account of backward compatibility. I agree.

**Comment by joebordes** [comment]
I use valitron in [coreBOS](https://github.com/tsolucio/corebos) and I would vote for dropping 5.x completely for version 2.x

**Comment by pocketpc** [comment]
I'm with KSVQ on this one. Keep 1.x around for older PHP versions, but move to 7+ for version 2.0.

**Comment by auroraeosrose** [comment]
Just to pile on - I'm +1 for branch old 1.x version as "last supported version for 5.x security/bug fixes only" and move along to the joy of 7 :)

**Comment by willemwollebrants** [comment]
I think it's pretty much decided by now: V2 will support 7.x and no more 5.x. Just need to find some time to get started for real :)
