### ISSUE TITLE
Github version different from composer version

### ISSUE THREAD

**Issue by realjay97** [vlucas/valitron#188]
The library version on github and that from packagist are different. The mapFieldRules and mapFieldsRules methods are not in the composer version.

**Comment by willemwollebrants** [comment]
The version of packagist is always the latest release (was v1.3.1), the code on github is "work in progress" (you could always tell composer to use dev-master, but I would not recommend that)

Since I'm working on a pretty big internal rewrite that will take a while I've decided to make a new release for mapFieldRules etc. just now. It should show up as v1.4.0 on packagist.  

Especially for you :)
