### ISSUE TITLE
"Accepted" Rule miss something

### ISSUE THREAD

**Issue by kaeh** [vlucas/valitron#191]
Hi, 
The "accepted" rule miss something to check. If you pass "true" as a string ($a = 'true'), this is not validated.

To handle this, just replace $acceptable variable in validateAccepted function from
```PHP
acceptable = array('yes', 'on', 1, '1', true);
```
to
```PHP
$acceptable = array('yes', 'on', 1, '1', true, 'true');
```

We had the problem on a webservice called by an angularjs that send true as string instead of a real boolean.

**Comment by willemwollebrants** [comment]
Good suggestion, but this would be a breaking change I'm afraid. I will add this to the next major version. 

In the meantime, you could probably use the 'in' rule:
```php
$validator = new \Valitron\Validator(['my_field'=>'true']);
$validator->rule('in', 'my_field', ['yes', 'on', 1, true, 'true'], true)->message('{field} must be accepted');
```
Note: the 4th parameter must be true to enable strict matching. Without it, any non-empty string would be matched by boolean true. Since 'false' is a non-empty string, this would be a problem.

**Comment by kaeh** [comment]
Ok, thanks for your answer ! :)
