### ISSUE TITLE
Optional and Required for the same field

### ISSUE THREAD

**Issue by jatubio** [vlucas/valitron#219]
Hello:

When I want that a field be required only if exists on the form, I add to them the rules 'required' and 'optional'. But when I don't include the field on the form, i'm getting the message: 'Field x is required'. It's this the expected behavior?

If the response is 'Yes', it will be a good idea to have one role for 'required only if filed exists'. 

Thank you

**Comment by willemwollebrants** [comment]
I think it's important to note that the validator actually validates an array. If a field is marked 'required', it must be present, not null and not be an empty string. 'Optional' means that the field MAY be present, and if it is it must pass the other rules. 

With that in mind, it seems illogical to have a field be both 'required' and 'optional' at the same time. I think what you want is to make the field 'optional', and use another rule to check if the content is what you expect. This means that the field MAY be present, and if it is, it must pass validation. 

So to answer our question: yes, this is expected behavior :)

**Comment by jatubio** [comment]
Thank you for your response.

In my web app, rules are loaded from a config file and some times i have one field that if is present can't be empty. But, if not present, don't have to pass other validation rules. I think that 'optional' overwrites 'required' rules and use both for these use cases.

Now i will make a new rule 'notempty' or similar and will use 'optional' and 'notempty' 😉 

Good weekend.
