### ISSUE TITLE
Required field does not work as optional

### ISSUE THREAD

**Issue by kazitanvirahsan** [vlucas/valitron#229]
I was reading the `readme` files of how to make required as optional. Validates only if the value exists.

Using an extra parameter, you can make this rule more flexible, and only check if the field exists in the data array.
$v->rule('required', 'field_name', true);

`<?php`
require 'vendor/autoload.php';
$v = new Valitron\Validator(array());
$v->rule('required', 'name',true);
if($v->validate()) {
    echo "Yay! We're all good!";
} else {
    // Errors
    print_r($v->errors());
}

echo 'Code `after';`

Validation always expects the value and generates validation messages. 

Is there any way to trigger required only if the value is supplied??

**Comment by willemwollebrants** [comment]
You can make sure the validations only run when a field is supplied by using the `optional` rule. This makes sure that if a field is supplied, it must pass all other validations for this field. If it's not supplied, all other rules are ignored (example: IF this field is present, THEN it MUST be a valid e-mail address).

But you can't make a field optionally required. A field is either required, or not.  "IF this field exists THEN IT MUST exist" does not make a lot of sense. 
(See also my reply at #219)

The third parameter for required switches between 'does this key exist, and is the value not empty' and simply 'does this key exist'. Example:
```php
$v = new Valitron\Validator(array('name'=>''));
$v->rule('required', 'name'); //this fails
$v->rule('required', 'name',true); //this passes
```
Your example fails validation because 'name' is required, but the key 'name' does not exist in the data array.
