### ISSUE TITLE
Empty Arrays Pass Required Rule

### ISSUE THREAD

**Issue by it-all** [vlucas/valitron#260]
I'm not sure if this is intended behavior. It seems proper to me that an empty array would fail required validation.

**Comment by vlucas** [comment]
Can you give a code example please?

**Comment by it-all** [comment]
Sure:
```
$v = new \Valitron\Validator(['testField' => []]);
$v->rule('required', 'testField');
if($v->validate()) {
    echo "Yay! We're all good!";
} else {
    // Errors
    print_r($v->errors());
}
```

// outputs: Yay! We're all good!

**Comment by willemwollebrants** [comment]
Looking at the code, this is expected. Here's the code that is used to validate required:
```php
if (is_null($value)) {
    return false;
} elseif (is_string($value) && trim($value) === '') {
    return false;
}
return true;
```
Everything that's not null and not an empty string will return true. The required rule only cares if the value is provided or not. The empty string thing is probably because the main use of Valitron is handling POST data. One solution is to make your rule more specific. If you expect a certain key, you can check for that key:
```php
//make sure $testField['my_expected_key'] is set
$v->rule('required', 'testField.my_expected_key');
```
If you want to make sure the array has at least one field, you can use numeric keys too:
```php
//make sure $testField[0] is set
$v->rule('required', 'testField.0');
```

If you want to be a bit more flexible, you can always use a callable too:
```php
$v->rule(function($field, $value){
return ! empty($value);
}, 'testField', 'testField must not be empty');
```

(having a built in validateNotEmpty rule in Valitron would probably be a good idea)

**Comment by it-all** [comment]
I figured it was something like that. It seems like a tough call on which way it should behave, as it does seem inconsistent with an empty string. Thanks for the workarounds!

**Comment by crtl** [comment]
I am having the same issue, for example:

```php
$rules = [
  "required" => ["username", "email", "password"],
   "slug" => "username",
   "email" => "email",
   "unique" => [
     ["email", $container["db"], "users", "email"]
   ],
   "lengthMin" => [
     ["email", 5]
    ]
];

$data = [
  "username" => null,
  "password" => null,
  "email" => null
];

$validator = new Validator($data);
$validator->rules($rules);
$validator->validate(); //True, should be false
```
