### ISSUE TITLE
Date validation ignoring leap-year issue

### ISSUE THREAD

**Issue by TanmayChakrabarty** [vlucas/valitron#315]
You validated date with `strtotime()`. This function doesn't consider leap-year. So if I send a value '2021-02-29' it will return true, as `strtotime('2021-02-29')` will produce an integer.

**Comment by willemwollebrants** [comment]
The problem is that '2021-02-29' is considered a valid date (equivalent to March 1st) by just about anything php-related I can think of. For example:
```php
echo DateTime::createFromFormat('Y-m-d','2021-02-29')->format('Y-m-d');
//outputs "2021-03-01"
```
So the **date** rule is really for checking if a piece of input could possibly be parsed as a date, and it can. 

If you can specify a format and use the **dateFormat** rule, it will give you the error you're looking for:
```php
$validator = new \Valitron\Validator([
    'test'=>'2021-02-29'
]);
$validator->rule('dateFormat', 'test', 'Y-m-d');

var_dump($validator->validate());
//bool(false)
var_dump($validator->errors());
/*
array(1) {
  ["test"]=>
  array(1) {
    [0]=>
    string(37) "Test must be date with format 'Y-m-d'"
  }
}
*/
```

**Comment by TanmayChakrabarty** [comment]
I disagree with your idea of a valid date, I mean the function was supposed to validate a date, and if the date was invalid it was supposed to return false, which isn't happening.
