### ISSUE TITLE
array_flip error on PHP 7.4

### ISSUE THREAD

**Issue by ngekoding** [vlucas/valitron#349]
I just trying to use this library, but got this error:

`
<b>Warning</b>:  array_flip(): Can only flip STRING and INTEGER values! in <b>/Users/nur/Devs/WebProjects/works@ftugm/notification-api/vendor/vlucas/valitron/src/Valitron/Validator.php</b> on line <b>104</b><br />
`

The errors comes when I use this code:

```php
$validator = new Validator($data, [
    'required' => ['subject']
]);
```

But working fine with this:

```php
$validator = new Validator($data);
$validator->rules([
    'required' => ['subject']
]);
```

I use PHP 7.4

How can we solve this?

Thanks in advance

**Comment by e5y** [comment]
It seems to me you're confusing the [**second parameter of the constructor**](https://github.com/vlucas/valitron/blob/9bf11f4374f722b78f69b1d36f5fd9154bb6bffa/src/Valitron/Validator.php#L104), which is meant for limiting unknown data to known fields, with the [**rules array**](https://github.com/vlucas/valitron/blob/9bf11f4374f722b78f69b1d36f5fd9154bb6bffa/src/Valitron/Validator.php#L1430), which is meant for declaring validation rules for each data field.

This helps populate the `$this->_fields` array (filters $data to only allow certain known fields, useful when validating against $_POST, $_GET, or any data outside of your control).

```php
$validator = new Validator($data, []);
```

This populates the `$this->_validations` array with field validation rules.

```php
$validator = new Validator($data);
$validator->rules([
    'required' => ['subject']
]);
```

Since you're using rule syntax, I'm guessing the second example is what you want, but just in case, here's how the first one works:

[**View full example in PHPSandbox**](https://phpsandbox.io/n/kr5mg)

```html
<form method="post">
    <input name="name" value="John">
    <input name="last_name" value="Doe">
    <button>Submit</button>
</form>
```
```php
<?php

use Valitron\Validator;

$validator1 = new Validator( $_POST );

var_dump($validator1->data());
// array(2) { ["name"]=> string(4) "John" ["last_name"]=> string(3) "Doe" }

$validator2 = new Validator( $_POST, [ 'name' ] );

var_dump($validator2->data());
// array(1) { ["name"]=> string(4) "John"}
```

**Comment by ngekoding** [comment]
Thank you, it is very clear.

So, it is my misunderstanding about the constructor parameters.
